 /*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `java-library`
    id("org.springframework.boot") version "3.1.1"

}

 group = "com.target"
 version = "0.0.1-SNAPSHOT"
 description = "EventManagement-api"

 java {
     sourceCompatibility = JavaVersion.VERSION_17 // Set the source compatibility to Java 17
     targetCompatibility = JavaVersion.VERSION_17 // Set the target compatibility to Java 17
 }
// java.sourceCompatibility = JavaVersion.VERSION_17

 sourceSets {
     main {
         java.srcDirs("src/main/java")
     }
     test {
         java.srcDirs("src/test/java")
     }
 }

 repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:3.1.1")
    implementation("org.springframework.boot:spring-boot-starter-web:3.1.1")
    implementation("org.postgresql:postgresql:42.6.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.1.1")
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
